// Player track sidebar.
//
// One file per track, and this is not cosmetic. All three docs plugins used to be pointed at this
// same file, and a docs plugin validates *every* sidebar key it is handed against its own folder.
// So the admin plugin was asked to resolve 'houses/building-a-house', which lives under docs/, and
// the build died listing two dozen "document ids do not exist" that all existed — just not in the
// folder doing the asking.
//
// Written by hand rather than autogenerated: reading order matters more than the alphabetical
// order of the folders, and "needs" has to come before "jobs" for the text to make sense.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  player: [
    'intro',
    'installation',
    'getting-started',
    {
      type: 'category',
      label: 'Houses',
      items: ['houses/building-a-house', 'houses/beds-and-residents', 'houses/villages'],
    },
    {
      type: 'category',
      label: 'The NPCs',
      items: [
        'npcs/needs',
        'npcs/personality-and-tastes',
        'npcs/jobs-and-hobbies',
        'npcs/relationships',
        'npcs/family-and-growth',
      ],
    },
    'interacting',
    'items',
    'faq',
  ],
};

module.exports = sidebars;
