// Sidebars for the three tracks.
//
// Written by hand rather than autogenerated: reading order matters more than the alphabetical
// order of the folders, and "needs" has to come before "jobs" for the text to make sense.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  player: [
    'intro',
    'installation',
    'getting-started',
    {
      type: 'category',
      label: 'Houses',
      items: ['houses/building-a-house', 'houses/beds-and-residents', 'houses/villages'],
    },
    {
      type: 'category',
      label: 'The NPCs',
      items: [
        'npcs/needs',
        'npcs/personality-and-tastes',
        'npcs/jobs-and-hobbies',
        'npcs/relationships',
        'npcs/family-and-growth',
      ],
    },
    'interacting',
    'faq',
  ],

  admin: [
    'intro',
    'commands',
    'generative-ai',
    'balancing',
    'troubleshooting',
  ],

  dev: [
    'intro',
    'ecs-architecture',
    'build-environment',
    {
      type: 'category',
      label: 'Systems',
      items: [
        'systems/routine-ai',
        'systems/furniture-registry',
        'systems/hunger-and-sleep',
        'systems/houses',
        'systems/villages',
        'systems/persistence',
      ],
    },
    {
      type: 'category',
      label: 'Recipes',
      items: [
        'recipes/add-a-job',
        'recipes/add-a-hobby',
        'recipes/add-a-command',
      ],
    },
    'lessons-learned',
  ],
};

module.exports = sidebars;
