package com.cookieukw.SimTale.systems;

import com.cookieukw.SimTale.SimTale;
import com.cookieukw.SimTale.config.SimTaleConfigManager;
import com.cookieukw.SimTale.core.SimLog;
import com.cookieukw.SimTale.core.SimNPCComponent;
import com.cookieukw.SimTale.core.SimNPCFactory;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.server.core.modules.entity.component.PersistentModel;
import com.hypixel.hytale.server.core.modules.time.WorldTimeResource;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;

/**
 * Automatic calendar trigger for seasonal event costumes (Christmas/Halloween), plus shared
 * apply/remove costume logic -- used by both this automatic trigger and the manual
 * "/simtale costume" command in SimTaleCommand.java, ensuring the two never disagree on what
 * an NPC is actually wearing (a single backup map, a single "active event" map).
 * The calendar comes from {@link WorldTimeResource#getGameDateTime()}, already used in
 * NPCSleepHelper/InteractionManager -- see docs/experimentos.md / wiki/dev/experiments.md
 * (section "automatic calendar trigger", 13/09) for full reasoning, including the two gotchas:
 * getMoonPhase() is not a named phase, and isYearWithinRange() has an unimplemented TODO
 * (which is why dates below are manually compared by month/day rather than using that method).
 * Each costumed NPC uses an asset generated by scripts/generate_costume_assets.py, whose "Parent"
 * points to that specific NPC's own model id -- see the same docs section for why
 * (prevents all costumed NPCs from having the same generic face). The asset also repeats the
 * NPC's whole DefaultAttachments list before the hat: that field replaces the parent's instead of
 * adding to it, and with only the hat listed a costumed NPC lost her eyes, mouth, hair and clothes.
 *
 * <p>Costume ids are always {@code <npc model id>_<event>}, so the original model can be read back
 * from the id itself ({@link #baseOf}). The in-memory maps below are lost on a restart; without
 * that fallback an NPC saved in costume could never be undressed, and dressing her for the other
 * event looked for {@code <id>_Christmas_Halloween}.
 */
public final class SeasonalCostumeHelper {

    private SeasonalCostumeHelper() {}

    private static final SimLog LOGGER = SimLog.forClass(SeasonalCostumeHelper.class);

    /**
     * Only runs calendar reading once every so many ticks -- other NPCs on the same global tick
     * simply check the cache below and return, rather than repeating the clock read.
     * ~1200 ticks = ~1 min real-time at 20 ticks/s; doesn't need to be more frequent, dates
     * don't change fast.
     */
    private static final long CHECK_INTERVAL_TICKS = 1200;

    private static long lastCheckedTick = -1;

    /** entityId -> model id BEFORE costume, so "off"/reversion can restore accurately. */
    public static final Map<UUID, String> COSTUME_BACKUP_MODEL = new HashMap<>();

    /**
     * entityId -> costume event CURRENTLY applied ("Christmas"/"Halloween"), absent if the NPC
     * is not in costume. Kept separate from the backup above so the automatic trigger can know
     * without re-reading PersistentModel whether this NPC is already in the right event.
     */
    public static final Map<UUID, String> ACTIVE_COSTUME_EVENT = new HashMap<>();

    /** NPCs whose costume was manually set via command, so automatic reconcile doesn't strip it. */
    public static final Set<UUID> MANUAL_COSTUMES = new java.util.HashSet<>();

    /**
     * Decides which event (if any) is active for the given date.
     * EXAMPLE dates, feel free to adjust here: entire December for Christmas, last week of
     * October for Halloween. Intentionally avoiding crossing month/year boundaries to keep the
     * comparison simple to audit without a compiler.
     */
    @Nullable
    public static String resolveEvent(@Nonnull LocalDateTime date) {
        int month = date.getMonthValue();
        int day = date.getDayOfMonth();

        // Christmas: entire month of December
        if (month == 12) {
            return "Christmas";
        }
        // Halloween: October 24 to 31
        if (month == 10 && day >= 24) {
            return "Halloween";
        }

        return null;
    }

    private static final String[] EVENTS = {"Christmas", "Halloween"};

    /** The event of a costume model id ("..._12_Christmas" -> "Christmas"), or null. */
    @Nullable
    public static String eventOf(@Nullable String modelId) {
        if (modelId == null) return null;
        for (String event : EVENTS) {
            if (modelId.endsWith("_" + event)) return event;
        }
        return null;
    }

    /** The NPC's own model id behind a costume id ("..._12_Christmas" -> "..._12"); other ids unchanged. */
    @Nonnull
    public static String baseOf(@Nonnull String modelId) {
        String event = eventOf(modelId);
        return event == null ? modelId : modelId.substring(0, modelId.length() - event.length() - 1);
    }

    /**
     * Called on each NPC tick by SimTaleTickSystem. Cheap when there's nothing to do: a single
     * long comparison and, in the vast majority of ticks, immediate return.
     */
    public static void tick(@Nonnull Store<EntityStore> store, long absoluteTick) {
        if (!SimTaleConfigManager.getConfig().seasonalCostumesEnabled) {
            if (!ACTIVE_COSTUME_EVENT.isEmpty()) {
                reconcileAll(store, null);
            }
            return;
        }
        if (absoluteTick % CHECK_INTERVAL_TICKS != 0 || absoluteTick == lastCheckedTick) return;
        lastCheckedTick = absoluteTick;

        WorldTimeResource time = store.getResource(WorldTimeResource.getResourceType());

        String currentEvent = resolveEvent(time.getGameDateTime());
        reconcileAll(store, currentEvent);
    }

    /**
     * Iterates over every active NPC and ensures she is wearing what she should: applies the
     * current event to those who don't have it yet, removes from those with a wrong/stale event,
     * and leaves alone those already correct. Also public so it can be called manually
     * (e.g. a future debug command) without waiting for the next automatic tick interval.
     */
    public static void reconcileAll(@Nonnull Store<EntityStore> store, @Nullable String currentEvent) {
        for (SimNPCComponent npc : SimTale.ACTIVE_NPCS) {
            if (npc.entityRef == null || !npc.entityRef.isValid() || npc.isReaper) continue;
            if (MANUAL_COSTUMES.contains(npc.entityId)) continue; // manually equipped costume

            Ref<EntityStore> npcRef = npc.entityRef;
            String activeEvent = ACTIVE_COSTUME_EVENT.get(npc.entityId);
            if (activeEvent == null) {
                // after a restart the map is empty, but a costume saved with the world is in the id
                PersistentModel pm = store.getComponent(npcRef, PersistentModel.getComponentType());
                if (pm != null) activeEvent = eventOf(pm.getModelReference().getModelAssetId());
            }
            if (Objects.equals(activeEvent, currentEvent)) continue; // already correct, nothing to do

            if (activeEvent != null) {
                removeCostume(store, npcRef, npc);
            }
            if (currentEvent != null) {
                applyCostume(store, npcRef, npc, currentEvent);
            }
        }
    }

    /**
     * Applies the given event costume to this NPC, storing the original model for later "off"/reversion.
     * Returns false (without changing anything) if the generated asset does not exist -- for example,
     * an NPC with a model id outside the default set that scripts/generate_costume_assets.py covers
     * (should be rare: the script covered every id found in Generated/ when run).
     */
    public static boolean applyCostume(@Nonnull Store<EntityStore> store, @Nonnull Ref<EntityStore> npcRef,
            @Nonnull SimNPCComponent npc, @Nonnull String event) {
        PersistentModel pm = store.getComponent(npcRef, PersistentModel.getComponentType());
        if (pm == null) return false;

        String currentId = pm.getModelReference().getModelAssetId();
        float scale = pm.getModelReference().getScale();
        // already in a costume (this session or saved with the world): dress the NPC underneath
        String baseId = COSTUME_BACKUP_MODEL.getOrDefault(npc.entityId, baseOf(currentId));
        String costumeId = baseId + "_" + event;

        boolean ok = costumeId.equals(currentId)
                || SimNPCFactory.applyModel(store, npcRef, costumeId, scale, new HashMap<>());
        if (ok) {
            COSTUME_BACKUP_MODEL.put(npc.entityId, baseId);
            ACTIVE_COSTUME_EVENT.put(npc.entityId, event);
            LOGGER.debug("[SimTale] " + npc.name + " automatically dressed for event '" + event + "'.");
        } else {
            LOGGER.warn("[SimTale] Failed to dress " + npc.name + " for event '" + event
                    + "' -- asset '" + costumeId + "' not found. Run scripts/generate_costume_assets.py.");
        }
        return ok;
    }

    /**
     * Restores this NPC's original model, if she has a saved backup. Silent no-op
     * (returns false) if there is no backup -- for example, a removal called when the NPC
     * was not costumed.
     */
    public static boolean removeCostume(@Nonnull Store<EntityStore> store, @Nonnull Ref<EntityStore> npcRef,
            @Nonnull SimNPCComponent npc) {
        String original = COSTUME_BACKUP_MODEL.remove(npc.entityId);
        ACTIVE_COSTUME_EVENT.remove(npc.entityId);
        MANUAL_COSTUMES.remove(npc.entityId);

        PersistentModel pm = store.getComponent(npcRef, PersistentModel.getComponentType());
        if (original == null && pm != null) {
            // no backup (restart): a costume id still says which model is underneath
            String currentId = pm.getModelReference().getModelAssetId();
            if (eventOf(currentId) != null) original = baseOf(currentId);
        }
        if (original == null) return false;
        float scale = pm != null ? pm.getModelReference().getScale() : 1f;

        boolean ok = SimNPCFactory.applyModel(store, npcRef, original, scale, new HashMap<>());
        if (!ok) {
            LOGGER.warn("[SimTale] Falha ao remover fantasia de " + npc.name + " -- modelo original '"
                    + original + "' nao encontrado.");
        }
        return ok;
    }
}
